In [1]:
import pandas as pd

In [2]:
our_table = pd.read_csv('dataset_with_tones.csv')
our_table.head()

    0        5
0   爱      аи4
1  爱好  аи4хао4
2   八      ба1
3  爸爸   ба4ба4
4   爸      ба4

In [4]:
reference_table = pd.read_csv('reference.csv')[['Иероглиф', 'Цифровое обозначение тонов']]
reference_table.head()

  Иероглиф Цифровое обозначение тонов
0        爱                        ай4
1        八                        ба1
2        爸                        ба4
3       爸爸                     ба4ба5
4        杯                       бэй1

In [5]:
def merge_cols(a, b):
    index_a = [entry[1]['0'] for entry in a.iterrows()]
    index_b = [entry[1]['Иероглиф'] for entry in b.iterrows()]
    a = [entry[1]['5'] for entry in a.iterrows()]

    b = [entry[1]['Цифровое обозначение тонов'] for entry in b.iterrows()]

    present_in_b = []
    for entry in index_b:
        if entry in index_a:
            present_in_b.append(a[index_a.index(entry)])
        else:
            # Логи о пропущенных нами иероглифах
            # print(f'Entry {entry} is not found!')
            present_in_b.append(pd.NaT)
        
    return pd.DataFrame(
        {'Иероглиф': index_b, 'Лингвистика': b, 'Наше решение': present_in_b}
    )

In [7]:
result_dataset = merge_cols(our_table, reference_table)
result_dataset

    Иероглиф  Лингвистика Наше решение
0          爱          ай4          аи4
1          八          ба1          ба1
2          爸          ба4          ба4
3         爸爸       ба4ба5       ба4ба4
4          杯         бэй1         беи1
..       ...          ...          ...
234       桌子   джуо1 дзы5       чо1зи3
235        字         дзы4         тзы4
236       昨天  дзуо2 тъен1    цзо2тиан1
237        坐        дзуо4         цзо4
238        做        дзуо4          NaT

[239 rows x 3 columns]

In [8]:
# Раскомментировать, если понадобится избавиться от упущенных нами иероглифов
# result_dataset.dropna(inplace=True)
# result_dataset.reset_index(drop=True)

# Сохранение датасета
result_dataset.to_csv(path_or_buf='./quality_assurance.csv', index=False)